#!/usr/bin/env bash

LFS=/mnt/lfs

cd ${LFS}/sources

./binutils-2.41.acf
pushd binutils
    mkdir -v build && cd build
    ../configure --prefix=${LFS}/tools \
        --with-sysroot=${LFS} \
        --target=${LFS_TGT} \
        --disable-nls \
        --enable-gprofng=no \
        --disable-werror
    make
    make install
popd
rm binutils