#!/usr/bin/env bash

pkgname="bzip3"
pkgver="git"
baseurl="https://github.com/kspalaiologos"

git clone ${baseurl}/${pkgname}.git

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname}
