#!/usr/bin/env bash

pkgname="file"
pkgver="5.45"
baseurl="https://astron.com/pub/file"

wget ${baseurl}/${pkgname}-${pkgver}.tar.gz

tar xvf ${pkgname}-${pkgver}.tar.gz
mv ${pkgname}-${pkgver} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.gz
