#!/usr/bin/env bash

pkgname="gdbm"
pkgver="1.23"
baseurl="https://ftp.gnu.org/gnu/gdbm"

wget ${baseurl}/${pkgname}-${pkgver}.tar.gz

tar xvf ${pkgname}-${pkgver}.tar.gz
mv ${pkgname}-${pkgver} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.gz
