#!/usr/bin/env bash

pkgname="grub"
pkgver="2.06"
baseurl="https://ftp.gnu.org/gnu/grub"

wget ${baseurl}/${pkgname}-${pkgver}.tar.xz

tar xvf ${pkgname}-${pkgver}.tar.xz
mkdir tmp_${pkgname}
mv ${pkgname}-${pkgver} tmp_${pkgname}/${pkgname}
pushd tmp_${pkgname}
	wget https://www.linuxfromscratch.org/patches/lfs/development/grub-2.06-upstream_fixes-1.patch
popd
mv tmp_${pkgname} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.xz
