#!/usr/bin/env bash

pkgname="libxcrypt"
pkgver="4.4.36"
baseurl="https://github.com/besser82/${pkgname}/releases/download/v${pkgver}"

wget ${baseurl}/${pkgname}-${pkgver}.tar.xz

tar xvf ${pkgname}-${pkgver}.tar.xz
mv ${pkgname}-${pkgver} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.xz
