#!/usr/bin/env bash

pkgname="psmisc"
pkgver="23.6"
baseurl="https://sourceforge.net/projects/${pkgname}/files/${pkgname}"

wget ${baseurl}/${pkgname}-${pkgver}.tar.xz

tar xvf ${pkgname}-${pkgver}.tar.xz
mv ${pkgname}-${pkgver} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.xz
