#!/usr/bin/env bash

pkgname="readline"
pkgver="8.2"
baseurl="https://ftp.gnu.org/gnu/${pkgname}"

wget ${baseurl}/${pkgname}-${pkgver}.tar.gz

tar xvf ${pkgname}-${pkgver}.tar.gz
mkdir tmp_${pkgname}
mv ${pkgname}-${pkgver} tmp_${pkgname}/${pkgname}
pushd tmp_${pkgname}
	wget https://www.linuxfromscratch.org/patches/lfs/development/readline-8.2-upstream_fixes-2.patch
popd
mv tmp_${pkgname} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.gz
