#!/usr/bin/env bash

pkgname="sysvinit"
pkgver="3.08"
baseurl="https://github.com/slicer69/sysvinit/releases/download/3.08"

wget ${baseurl}/${pkgname}-${pkgver}.tar.xz

tar xvf ${pkgname}-${pkgver}.tar.xz
mkdir tmp_${pkgname}
mv ${pkgname}-${pkgver} tmp_${pkgname}/${pkgname}
pushd tmp_${pkgname}
	wget https://www.linuxfromscratch.org/patches/lfs/development/sysvinit-3.08-consolidated-1.patch
popd
mv tmp_${pkgname} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.xz
