#!/usr/bin/env bash

pkgname="tcl"
pkgver="8.6.13"
baseurl="https://downloads.sourceforge.net/${pkgname}"

wget ${baseurl}/${pkgname}${pkgver}-html.tar.gz

tar xvf ${pkgname}${pkgver}-html.tar.gz
mv ${pkgname}${pkgver} ${pkgname}-html

makeself --bzip3 --notemp ./${pkgname}-html ./${pkgname}-docs-${pkgver}.acf "${pkgname}-docs v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname}-html ${pkgname}${pkgver}-html.tar.gz
