#!/usr/bin/env bash

pkgname="bzip2"
pkgver="1.0.8"
baseurl="https://www.sourceware.org/pub/bzip2"

wget ${baseurl}/${pkgname}-${pkgver}.tar.gz

tar xvf ${pkgname}-${pkgver}.tar.gz
mkdir tmp_${pkgname}
mv ${pkgname}-${pkgver} tmp_${pkgname}/${pkgname}
pushd tmp_${pkgname}
	wget https://www.linuxfromscratch.org/patches/lfs/development/bzip2-1.0.8-install_docs-1.patch
popd
mv tmp_${pkgname} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.gz
