#!/usr/bin/env bash

pkgname="flit_core"
pkgver="3.9.0"
baseurl="https://pypi.org/packages/source/f/flit-core"

wget ${baseurl}/${pkgname}-${pkgver}.tar.gz

tar xvf ${pkgname}-${pkgver}.tar.gz
mv ${pkgname}-${pkgver} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.gz
