#!/usr/bin/env bash

pkgname="kbd"
pkgver="2.6.4"
baseurl="https://www.kernel.org/pub/linux/utils/${pkgname}"

wget ${baseurl}/${pkgname}-${pkgver}.tar.xz

tar xvf ${pkgname}-${pkgver}.tar.xz
mkdir tmp_${pkgname}
mv ${pkgname}-${pkgver} tmp_${pkgname}/${pkgname}
pushd tmp_${pkgname}
	wget https://www.linuxfromscratch.org/patches/lfs/development/kbd-2.6.4-backspace-1.patch
popd
mv tmp_${pkgname} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.xz
