#!/usr/bin/env bash

pkgname="shadow"
pkgver="4.14.2"
baseurl="https://github.com/${pkgname}-maint/${pkgname}/releases/download/${pkgver}"

wget ${baseurl}/${pkgname}-${pkgver}.tar.xz

tar xvf ${pkgname}-${pkgver}.tar.xz
mv ${pkgname}-${pkgver} ${pkgname}

makeself --bzip3 --notemp ./${pkgname} ./${pkgname}-${pkgver}.acf "${pkgname} v. ${pkgver} SFX" echo "Extraction of ${pkgname} is Complete"

rm -rf ${pkgname} ${pkgname}-${pkgver}.tar.xz
