#!/usr/bin/env bash

printf "
######################################
#               WARNING              #
######################################
#   This script creates a new user   #
#  This could potentially kick your  #
#  puppy and eat your cat.  Do not   #
#     execute without examining      #
######################################
"
sleep 5

sudo groupadd lfs
sudo useradd -s /bin/bash -g lfs -m -k /dev/null -S lfs
sudo passwd lfs

sudo chown -v lfs ${LFS}/{usr{,/*},lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  x86_64) sudo chown -v lfs ${LFS}/lib64 ;;
esac

su - lfs